name: Node.js CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy using ssh
        uses: 98hub/ci-cd-nodejs@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }} 
          port: 22
          script: |
            cd /home/jelastic/ROOT
            git pull origin master
            git status
            npm install --only=prod
            pm2 restart 0
